"""
In-Blender runbook for Issue #22: validate pipeline behavior when the source
armature has fewer bones than the ASAM minimum.

WARNING - DESTRUCTIVE: this script removes bones from the in-memory source
armature. Run it in a fresh Blender session and CLOSE WITHOUT SAVING.

Usage:
  1. In VS Code: `Blender: Start`.
  2. In Blender: File -> Open -> sample_assets/LowPolyCharacter4.blend
  3. In VS Code: open this file, then `Blender: Run Script`.

The script:
  - Deletes Upper_Spine subdivisions plus all hand/foot bones from the source rig.
  - Runs the full pipeline (inspector -> classifier -> builder).
  - Asserts: builder completes without traceback, mesh_warnings is populated,
    each missing core target appears in classifier semantic mapping as a
    non-recoverable action, and all 28 ASAM core bones still exist in the
    generated armature (built via mirror/extrapolation).
  - Writes `docs/testing/reduced_rig_report.md` summarizing the resolution per
    target against the ASAM 7.3 core list.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.append(_HERE)

import bpy  # noqa: E402

from _harness import (  # noqa: E402
    DOCS_TESTING,
    ensure_src_on_path,
    reload_pipeline_modules,
    run_full_pipeline,
)
from _reduced_rig import LOWPOLY_REDUCED_DELETIONS, reduce_armature_in_place  # noqa: E402


SOURCE_ARMATURE_NAME = "rig"  # matches LowPolyCharacter4 source rig

# Core targets that should become unrecoverable once we drop hands/feet/spine
# subdivisions on the source. The classifier should mark each of these with an
# action other than direct_map (review, repair_in_builder, or create_in_builder)
# AND the builder should still produce geometry for them via mirror/extrapolation.
EXPECTED_DEGRADED_TARGETS = {
    "Upper_Spine",
    "Hand_Left",
    "Hand_Right",
    "Foot_Left",
    "Foot_Right",
    "Full_Toes_Left",
    "Full_Toes_Right",
    "Full_Fingers_Left",
    "Full_Fingers_Right",
    "Full_Thumb_Left",
    "Full_Thumb_Right",
}

RECOVERABLE_ACTIONS = {"direct_map", "alias_map", "repair_in_builder"}


def _summarize_classifier_actions(classifier_report: dict) -> dict:
    semantic_mapping = classifier_report.get("semantic_mapping", {})
    return {
        target: {
            "action": payload.get("action"),
            "source_bone": payload.get("source_bone"),
            "notes": list(payload.get("notes", [])),
        }
        for target, payload in semantic_mapping.items()
    }


def _summarize_builder_targets(builder_report: dict) -> dict:
    return {
        bone_name: "source"
        for bone_name in builder_report.get("targets_from_source_geometry", [])
    } | {
        bone_name: "heuristic"
        for bone_name in builder_report.get("targets_created_heuristically", [])
    }


def _write_report(
    classifier_summary: dict,
    builder_targets: dict,
    builder_report: dict,
    deleted_bones: list,
    overall_pass: bool,
) -> Path:
    DOCS_TESTING.mkdir(parents=True, exist_ok=True)
    report_path = DOCS_TESTING / "reduced_rig_report.md"
    lines = [
        "# Reduced-rig validation report (Issue #22)",
        "",
        "Generated by `tests/blender_runbook/test_reduced_source_rig.py`.",
        "",
        "## Source bones removed",
        "",
    ]
    for name in deleted_bones:
        lines.append("- `{0}`".format(name))
    lines.extend(
        [
            "",
            "## Target resolution",
            "",
            "| ASAM target | Classifier action | Source bone | Builder strategy |",
            "| --- | --- | --- | --- |",
        ]
    )
    for target in sorted(classifier_summary.keys()):
        payload = classifier_summary[target]
        strategy = builder_targets.get(target, "(missing)")
        lines.append(
            "| {target} | {action} | {source} | {strategy} |".format(
                target=target,
                action=payload["action"] or "-",
                source=payload["source_bone"] or "-",
                strategy=strategy,
            )
        )

    lines.extend(["", "## Builder warnings", ""])
    warnings = builder_report.get("warnings", [])
    if warnings:
        for warning in warnings:
            lines.append("- `{0}`".format(warning))
    else:
        lines.append("None.")

    lines.extend(["", "## Mesh warnings", ""])
    mesh_warnings = builder_report.get("mesh_warnings", [])
    if mesh_warnings:
        for warning in mesh_warnings:
            lines.append("- `{0}`".format(warning))
    else:
        lines.append("None.")

    lines.extend(["", "## Built core targets", ""])
    built = builder_report.get("built_core_targets", [])
    lines.append("{0} of 28 ASAM core bones produced.".format(len(built)))

    lines.extend(["", "## Overall", "", "**{0}**".format("PASS" if overall_pass else "FAIL")])
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report_path


def main() -> None:
    print("=" * 60)
    print("REDUCED SOURCE-RIG RUNBOOK - LowPolyCharacter4 (Issue #22)")
    print("=" * 60)
    print("WARNING: this script destructively edits the in-memory rig.")
    print("         Close Blender WITHOUT saving when done.")
    print("=" * 60)

    ensure_src_on_path()
    reload_pipeline_modules()

    armature_obj = bpy.data.objects.get(SOURCE_ARMATURE_NAME)
    if armature_obj is None or armature_obj.type != "ARMATURE":
        raise RuntimeError(
            "Expected source armature '{0}' is not in the open scene. "
            "Open sample_assets/LowPolyCharacter4.blend first.".format(SOURCE_ARMATURE_NAME)
        )

    deleted = reduce_armature_in_place(bpy, armature_obj, LOWPOLY_REDUCED_DELETIONS)
    print("Deleted {0} bones from source rig: {1}".format(len(deleted), ", ".join(deleted)))

    pipeline_result = run_full_pipeline(bpy)
    asset_dir = pipeline_result["asset_dir"]

    classifier_report_path = asset_dir / "classifier_report.json"
    with classifier_report_path.open("r", encoding="utf-8") as handle:
        classifier_report = json.load(handle)

    classifier_summary = _summarize_classifier_actions(classifier_report)
    builder_report = pipeline_result["builder_report"]
    builder_targets = _summarize_builder_targets(builder_report)

    overall_pass = True

    # Each expected-degraded target must NOT be a direct_map (source bone gone).
    for target in EXPECTED_DEGRADED_TARGETS:
        action = classifier_summary.get(target, {}).get("action")
        if action == "direct_map":
            print(
                "FAIL classifier still resolves '{0}' to direct_map after deletion".format(target)
            )
            overall_pass = False

    # Builder must still produce all 28 core targets.
    built = set(builder_report.get("built_core_targets", []))
    missing = sorted(EXPECTED_DEGRADED_TARGETS - built)
    if missing:
        # Only fail if any ASAM core target is missing - degraded ones should still be in built_core_targets
        print("FAIL builder did not produce these core targets: {0}".format(", ".join(missing)))
        overall_pass = False

    # mesh_warnings should be populated since most extremities are unmapped.
    if not builder_report.get("mesh_warnings"):
        print(
            "WARN builder_report.mesh_warnings is empty - expected unmapped vertex groups "
            "for the deleted source bones."
        )

    report_path = _write_report(
        classifier_summary,
        builder_targets,
        builder_report,
        deleted,
        overall_pass,
    )
    print("Reduced-rig report written to: {0}".format(report_path))
    print("Overall: {0}".format("PASS" if overall_pass else "FAIL"))


if __name__ == "__main__":
    main()
else:
    main()
