name: Documentation Task
description: Create or update documentation (Wiki, README, diagrams, etc.)
title: "[Documentation] <short description>"
labels:
  - documentation
body:
  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What kind of documentation work is required?
      options:
        - Wiki page
        - README update
        - Architecture documentation
        - API documentation
        - Pipeline documentation
        - Diagram
        - Other
    validations:
      required: true

  - type: input
    id: related_page
    attributes:
      label: Related Page or Section
      description: If applicable, specify the wiki page or file path.
      placeholder: e.g., Wiki/Homepage or docs/pipeline.md

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what needs to be written or updated.
      placeholder: Explain the documentation changes needed.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define when this task is considered complete.
      placeholder: |
        - Page created or updated
        - Reviewed for accuracy
        - Linked from sidebar
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Include references, screenshots, related issues, or links.
