name: Implementation Task
description: Coding or technical development task
title: "[Implementation] "
labels: ["implementation"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What needs to be implemented?
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Constraints, dependencies, or references.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When is this task considered complete?
